---

   - name: Copy root www files over to target
     copy:
       src: '{{item}}'  
       dest: /var/www/html
       owner: root
       group: root
       mode: 0644
     loop: 
       - "{{ root_playbook_dir }}/var/www/html/index.html"
       - "{{ root_playbook_dir }}/var/www/html/script.js"
       - "{{ root_playbook_dir }}/var/www/html/style.css"

     tags: 
       - LearnLinuxNetworkingHacking1

   - name: Create /var/www/html/Tutorial directory
     file: path=/var/www/html/Tutorial state=directory mode=0755 owner=www-data group=www-data
     tags: 
       - LearnLinuxNetworkingHacking

   - name: Copy Tutorial www files over to target (hugo creates the static website content in the public directory)
     copy:
       src: "{{ root_playbook_dir }}/var/www/html/Tutorial/public/"  
       dest: /var/www/html/Tutorial
       owner: root
       group: root
       mode: 0644
     tags: 
       - LearnLinuxNetworkingHacking1

   - name: Modify the Tutorial/index.html file to replace the internal https links with http (We can turn on https in a later lesson to teach kids the value of encryption)
     ansible.builtin.replace:
       path: /var/www/html/Tutorial/index.html
       regexp: '(?:href=\\u0027https:)' 
       replace: "href=\u0027http:"

   - name: Remove fonts.googleapis.com references from the tutorial pages. (This may no longer be needed in the etch hugo theme note date 021223)
     ansible.builtin.replace:
       path: '{{item}}'
       regexp: '(?:@import "https:\/\/fonts\.googleapis\.com\/css2\?family=Inconsolata&display=swap";:)' 
       replace: "\n"
     loop: 
       - "/var/www/html/Tutorial/scanning/index.html"
       - "/var/www/html/Tutorial/access/index.html"
       - "/var/www/html/Tutorial/defacing/index.html"
       - "/var/www/html/Tutorial/wifibruteforceing/index.html"
       - "/var/www/html/Tutorial/mactutorial/index.html"
       - "/var/www/html/Tutorial/index.html"

   - name: Edit the index.html file with the 
     lineinfile:
       path: /var/www/html/index.html
       insertbefore: </body>
       line: "<li>Build Version: {{ version['Ver'] }}</a></li>"
     tags: 
     - os_config_files
     - DeviceRegistration

   - name: Increment /var/www/html/index.html contents to reflect build Name
     lineinfile:
       path: /var/www/html/index.html
       insertbefore: </body>
       line: "<li>Build Name: {{ version['Build'] }}</a></li>"
     tags: 
     - os_config_files
     - DeviceRegistration

   - name: Increment /var/www/html/index.html contents to reflect build Date
     lineinfile:
       path: /var/www/html/index.html
       insertbefore: </body>
       line: "<li>Build Date: {{ version['BuildDate'] }}</a></li>"
     tags: 
     - os_config_files
     - DeviceRegistration